Fix error with self-signed certs
While testing this package, I was unable to connect to one Gemini server because it was using a self-signed certificate with a legacy Common Name Field.

Error: `connecting to the server "drewdevault.com:1965": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0`

Example server: gemini://drewdevault.com